/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pedropuertas.ejercicio7pedropuertas;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.OutputStreamWriter;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Javir
 */
public class JugadorAdivina extends javax.swing.JFrame {

    /**
     * Creates new form JugadorAdivina
     */
    private static int identificador;
    private static Socket socketComunicacion;
    private static OutputStreamWriter flujoSalEscrituraAServidor;
    private static BufferedWriter bufferEscrituraAServidor;
    private static ObjectInputStream fentrada;

    private final static String COD_TEXTO = "UTF-8";
    static String host = "localhost";
    static int puerto = 6000;

    public JugadorAdivina() {
        initComponents();
        try {

            socketComunicacion = new Socket(host, puerto);
            // Inicializa un objeto ObjectInputStream para leer los datos enviados desde el servidor
            fentrada = new ObjectInputStream(socketComunicacion.getInputStream());

            // Inicializa un objeto BufferedWriter para escribir datos al servidor,
            // usando una OutputStreamWriter
            flujoSalEscrituraAServidor = new OutputStreamWriter(socketComunicacion.getOutputStream(), COD_TEXTO);
            bufferEscrituraAServidor = new BufferedWriter(flujoSalEscrituraAServidor);

            System.out.println("Conectado al servidor");
            // Lee el objeto Datos enviado por el servidor
            Datos datos = (Datos) fentrada.readObject();

            // Obtiene el identificador del jugador proporcionado por el servidor
            identificador = datos.getIdentificador();
            idField.setText("" + identificador);

        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(JugadorAdivina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSalir = new javax.swing.JButton();
        btEnviar = new javax.swing.JButton();
        numeroField = new javax.swing.JTextField();
        numeroLabel = new javax.swing.JLabel();
        resultadoLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        intentosLabel = new javax.swing.JLabel();
        intentosField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        btEnviar.setText("Enviar");
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });

        numeroLabel.setText("Introduce el número:");

        resultadoLabel.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        resultadoLabel.setText("ADIVINA UN NÚMERO ENTRE 1 Y 25");

        idLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        idLabel.setText("ID Jugador:");

        idField.setEditable(false);

        intentosLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        intentosLabel.setText("Intentos:");

        intentosField.setEditable(false);
        intentosField.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(resultadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(intentosLabel)
                                .addGap(33, 33, 33)
                                .addComponent(intentosField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numeroLabel)
                                .addGap(18, 18, 18)
                                .addComponent(numeroField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intentosLabel)
                    .addComponent(intentosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEnviar)
                    .addComponent(numeroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroLabel))
                .addGap(47, 47, 47)
                .addComponent(resultadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btSalir)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        //Cierra la ventana actual y liberara todos los recursos asociados
        dispose();
    }//GEN-LAST:event_btSalirActionPerformed

    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarActionPerformed

        String texto;

        texto = numeroField.getText();

        try {
            int numero = Integer.parseInt(texto);

            // Escribe el número en el buffer de escritura del cliente para enviarlo al servidor
            bufferEscrituraAServidor.write(texto);
            bufferEscrituraAServidor.newLine();
            bufferEscrituraAServidor.flush();

            // Lee los datos del objeto compartido enviado por el servidor
            Datos datos = (Datos) fentrada.readObject();

            // Actualiza la etiqueta del resultado con la cadena de texto devuelta por el servidor
            resultadoLabel.setText(datos.getCadena());

            // Actualiza la etiqueta del número de intentos con el valor devuelto por el servidor
            intentosField.setText(String.valueOf(datos.getIntentos()));

            // Si el número de intentos es igual a 5 o si hay un ganador, se desactiva el botón Enviar
            if (String.valueOf(datos.getIntentos()).equals("5") || datos.ganador()) {
                btEnviar.setEnabled(false);
            }

            // Muestra el estado del juego y los intentos actuales en la consola
            String mensaje = datos.getCadena();
            System.out.println("Estado del juego: " + mensaje + " \nIntentos: " + datos.getIntentos());

            // Cambia el color del campo de texto a blanco
            numeroField.setBackground(Color.white);

        } catch (NumberFormatException ex) {

            numeroField.setBackground(Color.red);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(JugadorAdivina.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btEnviarActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    public static void main(String args[]) throws IOException {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JugadorAdivina().setVisible(true);
        });

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JugadorAdivina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEnviar;
    private javax.swing.JButton btSalir;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField intentosField;
    private javax.swing.JLabel intentosLabel;
    private javax.swing.JTextField numeroField;
    private javax.swing.JLabel numeroLabel;
    private javax.swing.JLabel resultadoLabel;
    // End of variables declaration//GEN-END:variables
}
