/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.LoginController;
import controlador.MoverController;
import controlador.TablaController;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import modelo.Mensaje;

/**
 *
 * @author alumno
 */
public class PanelCuentas extends javax.swing.JPanel {

    public static int contador = 36;
    
    /**
     * Creates new form PanelCuentas
     */
    public PanelCuentas() {
        initComponents();
        
        MoverController.iniciar("SELECT * FROM CUENTA WHERE USUNUMERO = " + LoginController.getUsuario().getNumero());
        cargarDatos();
        updateBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCuentas = new javax.swing.JPanel();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnPrimero = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblMaximo = new javax.swing.JLabel();
        lblCoste = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        tfCodigo = new javax.swing.JTextField();
        dcFecha = new com.toedter.calendar.JDateChooser();
        tfMaximo = new javax.swing.JTextField();
        tfCoste = new javax.swing.JTextField();
        btnMensajes = new javax.swing.JButton();
        btnAddCuenta = new javax.swing.JButton();
        tfDestino = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        btnVolver = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        btnEnviarMensaje = new javax.swing.JButton();

        pnlCuentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        pnlCuentas.add(btnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 265, -1, -1));

        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        pnlCuentas.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 265, -1, -1));

        btnUltimo.setText(">|");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });
        pnlCuentas.add(btnUltimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 265, -1, -1));

        btnPrimero.setText("|<");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });
        pnlCuentas.add(btnPrimero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 265, -1, -1));

        lblCodigo.setText("Código:");
        pnlCuentas.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 47, -1, -1));

        lblEmail.setText("Email:");
        pnlCuentas.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 83, -1, -1));

        lblFecha.setText("Fecha alta:");
        pnlCuentas.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 117, -1, -1));

        lblMaximo.setText("Máximo mensajes:");
        pnlCuentas.add(lblMaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 156, -1, -1));

        lblCoste.setText("Coste extra:");
        pnlCuentas.add(lblCoste, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 192, -1, -1));
        pnlCuentas.add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 81, 170, -1));
        pnlCuentas.add(tfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 45, 99, -1));
        pnlCuentas.add(dcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 117, -1, -1));
        pnlCuentas.add(tfMaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 154, 99, -1));
        pnlCuentas.add(tfCoste, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 190, 99, -1));

        btnMensajes.setText("Ver Mensajes");
        btnMensajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMensajesActionPerformed(evt);
            }
        });
        pnlCuentas.add(btnMensajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 230, -1, -1));

        btnAddCuenta.setText("Añadir cuenta");
        btnAddCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCuentaActionPerformed(evt);
            }
        });
        pnlCuentas.add(btnAddCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));
        pnlCuentas.add(tfDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 90, -1));

        jList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList);

        pnlCuentas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 330, 170));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        pnlCuentas.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        btnEnviar.setText("Enviar mensaje");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        pnlCuentas.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        btnEnviarMensaje.setText("Enviar");
        btnEnviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarMensajeActionPerformed(evt);
            }
        });
        pnlCuentas.add(btnEnviarMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        MoverController.irPrimero();
        cargarDatos();
        updateBotones();
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        MoverController.retro();
        cargarDatos();
        updateBotones();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        MoverController.avanzar();
        cargarDatos();
        updateBotones();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        MoverController.irUltimo();
        cargarDatos();
        updateBotones();
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnMensajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensajesActionPerformed
        
        rellenarJList();
        
    }//GEN-LAST:event_btnMensajesActionPerformed

    private void btnAddCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCuentaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        cargarDatos();
        updateBotones();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        
        lblCodigo.setText("Asunto:");
        lblEmail.setText("Contenido:");
        lblFecha.setText("Destino:");
        
        tfCodigo.setText("");
        tfEmail.setText("");
        tfDestino.setText("");
        
        lblCodigo.setVisible(true);
        lblEmail.setVisible(true);
        lblFecha.setVisible(true);
        
        jList.setVisible(false);
        tfCodigo.setVisible(true);
        tfEmail.setVisible(true);
        
        tfCodigo.setVisible(true);
        tfEmail.setVisible(true);
        tfDestino.setVisible(true);
        
        tfCodigo.setEnabled(true);
        tfEmail.setEnabled(true);
        tfDestino.setEnabled(true);
        
        btnEnviarMensaje.setVisible(true);
        btnVolver.setVisible(true);
        btnEnviar.setVisible(false);
        
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnEnviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarMensajeActionPerformed
        
        enviarMensaje();
        cargarDatos();
        
    }//GEN-LAST:event_btnEnviarMensajeActionPerformed

    public void updateBotones(){
        
        if(MoverController.primero()){
            btnPrimero.setEnabled(false);
            btnAnterior.setEnabled(false);
        }else{
            btnPrimero.setEnabled(true);
            btnAnterior.setEnabled(true);
        }
        
        if(MoverController.ultimo()){
            btnUltimo.setEnabled(false);
            btnSiguiente.setEnabled(false);
        }else{
            btnUltimo.setEnabled(true);
            btnSiguiente.setEnabled(true);
        }
        
    }
    
    public void cargarDatos(){
        
        jList.setVisible(false);
        tfCodigo.setVisible(true);
        tfCoste.setVisible(true);
        tfEmail.setVisible(true);
        tfMaximo.setVisible(true);
        dcFecha.setVisible(true);
        lblCodigo.setVisible(true);
        lblCoste.setVisible(true);
        lblEmail.setVisible(true);
        lblFecha.setVisible(true);
        lblMaximo.setVisible(true);
        btnAddCuenta.setVisible(true);
        btnAnterior.setVisible(true);
        btnPrimero.setVisible(true);
        btnSiguiente.setVisible(true);
        btnUltimo.setVisible(true);
        btnMensajes.setVisible(true);
        btnVolver.setVisible(false);
        btnEnviar.setVisible(false);
        btnEnviarMensaje.setVisible(false);
        tfDestino.setVisible(false);
        
        lblCodigo.setText("Código:");
        lblEmail.setText("Email:");
        lblFecha.setText("Fecha alta:");
        
        tfCodigo.setEnabled(false);
        tfCoste.setEnabled(false);
        tfEmail.setEnabled(false);
        tfMaximo.setEnabled(false);
        dcFecha.setEnabled(false);
        
        tfCodigo.setText(""+MoverController.getCuenta().getCodigo());
        tfCoste.setText(""+MoverController.getCuenta().getCoste() + "€");
        tfEmail.setText(MoverController.getCuenta().getEmail());
        tfMaximo.setText("" + MoverController.getCuenta().getMaximo());
        dcFecha.setCalendar(MoverController.getCuenta().getFechaAlta());
        
    }
    
    public void rellenarJList(){
        
        ArrayList <Mensaje> lista;
        
        lista = TablaController.getMensajes(MoverController.getCuenta());
        
        DefaultListModel model = new DefaultListModel();
        
        for (int i = 0; i < lista.size(); i++) {
            model.addElement(lista.get(i).infoMensaje());
        }
        
        this.jList.setModel(model);
        jList.setVisible(true);
        tfCodigo.setVisible(false);
        tfCoste.setVisible(false);
        tfEmail.setVisible(false);
        tfMaximo.setVisible(false);
        tfDestino.setVisible(false);
        dcFecha.setVisible(false);
        lblCodigo.setVisible(false);
        lblCoste.setVisible(false);
        lblEmail.setVisible(false);
        lblFecha.setVisible(false);
        lblMaximo.setVisible(false);
        btnAddCuenta.setVisible(false);
        btnAnterior.setVisible(false);
        btnPrimero.setVisible(false);
        btnSiguiente.setVisible(false);
        btnUltimo.setVisible(false);
        btnMensajes.setVisible(false);
        btnVolver.setVisible(true);
        btnEnviar.setVisible(true);
        btnEnviarMensaje.setVisible(false);
        
    }
    
    public void enviarMensaje(){
        Mensaje j;
        
        int filas;
        
        String asunto, contenido;
        int destino;
        
        asunto = tfCodigo.getText();
        contenido = tfEmail.getText();
        destino = Integer.parseInt(tfDestino.getText());
        
        j = new Mensaje(contador, asunto, contenido, 0, new GregorianCalendar(), 
                MoverController.getCuenta().getCodigo(), destino);
        
        filas = TablaController.enviarMensaje(j);
        
        JOptionPane.showMessageDialog(null, "Mensajes insertados: " + filas);
        
        contador++;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCuenta;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnEnviarMensaje;
    private javax.swing.JButton btnMensajes;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JButton btnVolver;
    private com.toedter.calendar.JDateChooser dcFecha;
    private javax.swing.JList<String> jList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCoste;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMaximo;
    private javax.swing.JPanel pnlCuentas;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfCoste;
    private javax.swing.JTextField tfDestino;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfMaximo;
    // End of variables declaration//GEN-END:variables
}
