/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author alumno
 */
public class PanelUsuario extends javax.swing.JPanel {

    /**
     * Creates new form PanelUsuario
     */
    public PanelUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUsuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dcFecha = new com.toedter.calendar.JDateChooser();
        tfApellidos = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        lblFoto = new javax.swing.JLabel();

        pnlUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        pnlUsuario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 71, -1, -1));

        jLabel2.setText("Apellidos:");
        pnlUsuario.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 107, -1, -1));

        jLabel3.setText("Fecha nac:");
        pnlUsuario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 146, -1, -1));
        pnlUsuario.add(dcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 141, -1, -1));
        pnlUsuario.add(tfApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 105, 125, -1));
        pnlUsuario.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 69, 125, -1));

        lblFoto.setText("Foto");
        pnlUsuario.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 130, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dcFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JPanel pnlUsuario;
    private javax.swing.JTextField tfApellidos;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
