/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.GestionDB;
import javax.swing.JPanel;

/**
 *
 * @author alumno
 */
public class Principal extends javax.swing.JFrame {

    private PanelLogin pnlLogin;
    private PanelCuentas pnlCuentas;
    private PanelUsuario pnlUsuario;
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        
        menuLogin.setEnabled(true);
        itemCerrar.setEnabled(false);
        menuVista.setEnabled(false);
        pnlLogin = null;
        pnlCuentas = null;
        pnlUsuario = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblAutor = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblCurso = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuLogin = new javax.swing.JMenu();
        itemAbrir = new javax.swing.JMenuItem();
        itemCerrar = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();
        menuVista = new javax.swing.JMenu();
        itemCuentas = new javax.swing.JMenuItem();
        itemUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAutor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblAutor.setText("Pedro Puertas Rodríguez");

        btnLogin.setText("Loguear");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblCurso.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCurso.setText("2ºDAM");

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btnLogin))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lblAutor))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(lblCurso)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnLogin)
                .addGap(83, 83, 83))
        );

        menuLogin.setText("Login");

        itemAbrir.setText("Abrir");
        itemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAbrirActionPerformed(evt);
            }
        });
        menuLogin.add(itemAbrir);

        itemCerrar.setText("Cerrar");
        itemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarActionPerformed(evt);
            }
        });
        menuLogin.add(itemCerrar);

        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        menuLogin.add(itemSalir);

        jMenuBar1.add(menuLogin);

        menuVista.setText("Ver");

        itemCuentas.setText("Ver cuentas");
        itemCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCuentasActionPerformed(evt);
            }
        });
        menuVista.add(itemCuentas);

        itemUsuario.setText("Ver usuario");
        itemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsuarioActionPerformed(evt);
            }
        });
        menuVista.add(itemUsuario);

        jMenuBar1.add(menuVista);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAbrirActionPerformed
        
        pnlLogin = new PanelLogin(menuVista, itemAbrir, menuLogin, itemSalir);
        
        visualizar(pnlLogin);
        
    }//GEN-LAST:event_itemAbrirActionPerformed

    private void itemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarActionPerformed
        GestionDB.close();
        visualizar(pnlPrincipal);
        
        menuVista.setEnabled(false);
        itemAbrir.setEnabled(true);
        itemCerrar.setEnabled(false);
    }//GEN-LAST:event_itemCerrarActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        GestionDB.close();
        System.exit(0);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCuentasActionPerformed
        pnlCuentas = new PanelCuentas();
        visualizar(pnlCuentas);
    }//GEN-LAST:event_itemCuentasActionPerformed

    private void itemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuarioActionPerformed
        pnlUsuario = new PanelUsuario();
        visualizar(pnlUsuario);
    }//GEN-LAST:event_itemUsuarioActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
        pnlLogin = new PanelLogin(menuVista, itemAbrir, menuLogin, itemSalir);
        visualizar(pnlLogin);
        
    }//GEN-LAST:event_btnLoginActionPerformed

    public void visualizar(JPanel panel){
        this.setContentPane(panel);
        pack();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JMenuItem itemAbrir;
    private javax.swing.JMenuItem itemCerrar;
    private javax.swing.JMenuItem itemCuentas;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuItem itemUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JMenu menuLogin;
    private javax.swing.JMenu menuVista;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
