package model;
// Generated 07-mar-2023 20:24:20 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Autor generated by hbm2java
 */
public class Autor  implements java.io.Serializable {


     private int numero;
     private String nombre;
     private String apellido;
     private String passowrd;
     private String foto;
     private Date nacimiento;

    public Autor() {
    }

	
    public Autor(int numero) {
        this.numero = numero;
    }
    public Autor(int numero, String nombre, String apellido, String passowrd, String foto, Date nacimiento) {
       this.numero = numero;
       this.nombre = nombre;
       this.apellido = apellido;
       this.passowrd = passowrd;
       this.foto = foto;
       this.nacimiento = nacimiento;
    }
   
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getPassowrd() {
        return this.passowrd;
    }
    
    public void setPassowrd(String passowrd) {
        this.passowrd = passowrd;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public Date getNacimiento() {
        return this.nacimiento;
    }
    
    public void setNacimiento(Date nacimiento) {
        this.nacimiento = nacimiento;
    }




}


