package model;
// Generated 07-mar-2023 20:24:20 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Libro generated by hbm2java
 */
public class Libro  implements java.io.Serializable {


     private int codigo;
     private String titulo;
     private Date fechapublicacion;
     private Double precio;
     private String imagen;
     private Integer autnumero;

    public Libro() {
    }

	
    public Libro(int codigo) {
        this.codigo = codigo;
    }
    public Libro(int codigo, String titulo, Date fechapublicacion, Double precio, String imagen, Integer autnumero) {
       this.codigo = codigo;
       this.titulo = titulo;
       this.fechapublicacion = fechapublicacion;
       this.precio = precio;
       this.imagen = imagen;
       this.autnumero = autnumero;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Date getFechapublicacion() {
        return this.fechapublicacion;
    }
    
    public void setFechapublicacion(Date fechapublicacion) {
        this.fechapublicacion = fechapublicacion;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public Integer getAutnumero() {
        return this.autnumero;
    }
    
    public void setAutnumero(Integer autnumero) {
        this.autnumero = autnumero;
    }




}


