/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Visualizar;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author alumno
 */
public class Gestor extends javax.swing.JFrame {
    
    public static int codProfesor = 0;
    private VisualizaJList panelJList;
    private Visualiza1a1 panelUno;
    private Login panelLogin;
    
    /**
     * Creates new form Interfaz
     */
    public Gestor() {
        panelLogin = new Login();
        panelJList = new VisualizaJList();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeneral = new javax.swing.JPanel();
        labelConectado = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuConexion = new javax.swing.JMenu();
        itemAbrir = new javax.swing.JMenuItem();
        itemCerrar = new javax.swing.JMenuItem();
        menuVisualizar = new javax.swing.JMenu();
        item1a1 = new javax.swing.JMenuItem();
        itemDetalle = new javax.swing.JMenuItem();
        menuAcerca = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelConectado.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelConectado.setForeground(Color.RED);
        labelConectado.setText("Desconectado");

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeneralLayout.createSequentialGroup()
                .addContainerGap(303, Short.MAX_VALUE)
                .addComponent(labelConectado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelConectado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        menuConexion.setText("Conexion");

        itemAbrir.setText("Abrir");
        itemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAbrirActionPerformed(evt);
            }
        });
        menuConexion.add(itemAbrir);

        itemCerrar.setText("Cerrar");
        itemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarActionPerformed(evt);
            }
        });
        menuConexion.add(itemCerrar);
        itemCerrar.setEnabled(false);

        jMenuBar1.add(menuConexion);

        menuVisualizar.setText("Visualizar");

        item1a1.setText("1 a 1");
        item1a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item1a1ActionPerformed(evt);
            }
        });
        menuVisualizar.add(item1a1);

        itemDetalle.setText("Detalle");
        menuVisualizar.add(itemDetalle);

        jMenuBar1.add(menuVisualizar);
        menuVisualizar.setEnabled(false);

        menuAcerca.setText("Acerca de");
        menuAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcercaActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuAcerca);
        menuAcerca.setEnabled(false);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAbrirActionPerformed
        // TODO add your handling code here:
        visualizar(panelLogin);
        pack();
    }//GEN-LAST:event_itemAbrirActionPerformed

    private void menuAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcercaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuAcercaActionPerformed

    private void itemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarActionPerformed
        // TODO add your handling code here:
        cerrarConexion();
    }//GEN-LAST:event_itemCerrarActionPerformed

    private void item1a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item1a1ActionPerformed
        // TODO add your handling code here:
        panelUno = new Visualiza1a1(codProfesor);
        visualizar(panelUno);
    }//GEN-LAST:event_item1a1ActionPerformed

    public void visualizar(JPanel panel){
        this.setContentPane(panel);
    }
    
    public void comprobarConexion(){
        labelConectado.setForeground(new Color(33, 100, 0));
        labelConectado.setText("Conectado");
        menuVisualizar.setEnabled(true);
        menuAcerca.setEnabled(true);
        itemAbrir.setEnabled(false);
        itemCerrar.setEnabled(true);
    }
    
    public void cerrarConexion(){
        labelConectado.setForeground(Color.red);
        labelConectado.setText("Desconectado");
        menuVisualizar.setEnabled(false);
        menuAcerca.setEnabled(false);
        itemAbrir.setEnabled(true);
        itemCerrar.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem item1a1;
    private javax.swing.JMenuItem itemAbrir;
    private javax.swing.JMenuItem itemCerrar;
    private javax.swing.JMenuItem itemDetalle;
    private javax.swing.JMenuBar jMenuBar1;
    private java.awt.Label labelConectado;
    private javax.swing.JMenu menuAcerca;
    private javax.swing.JMenu menuConexion;
    private javax.swing.JMenu menuVisualizar;
    private javax.swing.JPanel panelGeneral;
    // End of variables declaration//GEN-END:variables
}
