/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.LoginController;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author alumno
 */
public class Gestor extends javax.swing.JFrame {
    
    public static int codProfesor = 0;
    private PanelResumen panelJList;
    private PanelDetalle panelUno;
    private Login panelLogin;
    private AcercaDe dialogAcerca;
    
    /**
     * Creates new form Interfaz
     */
    public Gestor() {
        panelLogin = null;
        panelUno = null;
        panelJList = null;
        
        initComponents();
    }

    public static int getCodProfesor() {
        return codProfesor;
    }

    public static void setCodProfesor(int codProfesor) {
        Gestor.codProfesor = codProfesor;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeneral = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuConexion = new javax.swing.JMenu();
        itemAbrir = new javax.swing.JMenuItem();
        itemCerrar = new javax.swing.JMenuItem();
        menuVisualizar = new javax.swing.JMenu();
        itemDetalle = new javax.swing.JMenuItem();
        itemResumen = new javax.swing.JMenuItem();
        menuAcerca = new javax.swing.JMenu();
        itemVer = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        menuConexion.setText("Conexion");

        itemAbrir.setText("Abrir");
        itemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAbrirActionPerformed(evt);
            }
        });
        menuConexion.add(itemAbrir);

        itemCerrar.setText("Cerrar");
        itemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarActionPerformed(evt);
            }
        });
        menuConexion.add(itemCerrar);
        itemCerrar.setEnabled(false);

        jMenuBar1.add(menuConexion);

        menuVisualizar.setText("Visualizar");

        itemDetalle.setText("Detalle");
        itemDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDetalleActionPerformed(evt);
            }
        });
        menuVisualizar.add(itemDetalle);

        itemResumen.setText("Resumen");
        itemResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemResumenActionPerformed(evt);
            }
        });
        menuVisualizar.add(itemResumen);

        jMenuBar1.add(menuVisualizar);
        menuVisualizar.setEnabled(false);

        menuAcerca.setText("Acerca de");

        itemVer.setText("Ver");
        itemVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerActionPerformed(evt);
            }
        });
        menuAcerca.add(itemVer);

        jMenuBar1.add(menuAcerca);
        menuAcerca.setEnabled(false);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAbrirActionPerformed
        // TODO add your handling code here:
        panelLogin = new Login(menuAcerca, menuVisualizar, itemAbrir, itemCerrar);
        visualizar(panelLogin);
        pack();
    }//GEN-LAST:event_itemAbrirActionPerformed

    private void itemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarActionPerformed
        // TODO add your handling code here:
        cerrarConexion();
    }//GEN-LAST:event_itemCerrarActionPerformed

    private void itemDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDetalleActionPerformed
        // TODO add your handling code here:
        panelUno = new PanelDetalle();
        visualizar(panelUno);
        pack();
    }//GEN-LAST:event_itemDetalleActionPerformed

    private void itemVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerActionPerformed
        dialogAcerca = new AcercaDe(this, true);
        dialogAcerca.setVisible(true);
    }//GEN-LAST:event_itemVerActionPerformed

    private void itemResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemResumenActionPerformed
        // TODO add your handling code here:
        visualizar(panelJList);
        pack();
    }//GEN-LAST:event_itemResumenActionPerformed

    public void visualizar(JPanel panel){
        this.setContentPane(panel);
    }
    
    public void comprobarConexion(){
        menuVisualizar.setEnabled(true);
        menuAcerca.setEnabled(true);
        itemAbrir.setEnabled(false);
        itemCerrar.setEnabled(true);
    }
    
    public void cerrarConexion(){
        menuVisualizar.setEnabled(false);
        menuAcerca.setEnabled(false);
        itemAbrir.setEnabled(true);
        itemCerrar.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAbrir;
    private javax.swing.JMenuItem itemCerrar;
    private javax.swing.JMenuItem itemDetalle;
    private javax.swing.JMenuItem itemResumen;
    private javax.swing.JMenuItem itemVer;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAcerca;
    private javax.swing.JMenu menuConexion;
    private javax.swing.JMenu menuVisualizar;
    private javax.swing.JPanel panelGeneral;
    // End of variables declaration//GEN-END:variables
}
