/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.LoginController;
import controlador.ResumenController;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import modelo.Asignatura;

/**
 *
 * @author alumno
 */
public class PanelResumen extends javax.swing.JPanel {

    /**
     * Creates new form VisualizaJList
     */
    public PanelResumen() {
        initComponents();
        
        rellenarDatosProf();
        rellenarJList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelResumen = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListAsig = new javax.swing.JList<>();
        labelFoto = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelCodigo = new javax.swing.JLabel();
        labelNota = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfCodigo = new javax.swing.JTextField();
        tfNota = new javax.swing.JTextField();
        botonCalcular = new javax.swing.JButton();
        labelHoras = new javax.swing.JLabel();
        tfHoras = new javax.swing.JTextField();
        labelFecha = new javax.swing.JLabel();
        dcFecha = new com.toedter.calendar.JDateChooser();

        jListAsig.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListAsig);

        labelNombre.setText("Nombre:");

        labelCodigo.setText("Código:");

        labelNota.setText("Nota media:");

        botonCalcular.setText("Calcular Media");
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });

        labelHoras.setText("Horas trabajadas:");

        labelFecha.setText("Fecha contrato:");

        javax.swing.GroupLayout panelResumenLayout = new javax.swing.GroupLayout(panelResumen);
        panelResumen.setLayout(panelResumenLayout);
        panelResumenLayout.setHorizontalGroup(
            panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResumenLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelResumenLayout.createSequentialGroup()
                        .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNota)
                            .addComponent(labelNombre)
                            .addComponent(labelCodigo)
                            .addComponent(labelHoras)
                            .addComponent(labelFecha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNota)
                            .addComponent(tfNombre)
                            .addComponent(tfCodigo)
                            .addComponent(tfHoras)
                            .addComponent(dcFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                        .addGap(84, 84, 84)
                        .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(panelResumenLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(botonCalcular)
                .addGap(48, 48, 48))
        );
        panelResumenLayout.setVerticalGroup(
            panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResumenLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResumenLayout.createSequentialGroup()
                        .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombre)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCodigo)
                            .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNota)
                            .addComponent(tfNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHoras)
                            .addComponent(tfHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFecha)))
                    .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(botonCalcular)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelResumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelResumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
        
        float media = ResumenController.getNotas(LoginController.getProf().getCodProfesor());
        
        ResumenController.updateMedia("UPDATE PROFESOR SET NOTACORTEMEDIA = " + media 
                + " WHERE CODPROFESOR = " + LoginController.getProf().getCodProfesor());
        
        rellenarDatosProf();
    }//GEN-LAST:event_botonCalcularActionPerformed


    public void rellenarJList(){
        ArrayList<Asignatura> lista = ResumenController.getLista("SELECT * FROM ASIGNATURA "
                + "WHERE CODPROFESOR = " + LoginController.getProf().getCodProfesor());
         
        DefaultListModel model = new DefaultListModel();
         
        for (int i = 0; i < lista.size(); i++) {
            model.addElement(lista.get(i).infoAsig());
        }
        this.jListAsig.setModel(model);
    }
    
    public void rellenarDatosProf(){
        tfNombre.setText("" + ResumenController.getProf().getNombre());
        tfCodigo.setText("" + ResumenController.getProf().getCodProfesor());
        tfNota.setText("" + ResumenController.getProf().getNotaCorteMedia());
        tfHoras.setText("" + ResumenController.getProf().getHoras());
        dcFecha.setCalendar(ResumenController.getProf().getFechaContrato());
        labelFoto.setIcon(new ImageIcon(System.getProperty("user.dir") 
                + "\\src\\fotos\\" + ResumenController.getProf().getFoto()));
        tfNombre.setEnabled(false);
        tfCodigo.setEnabled(false);
        tfNota.setEnabled(false);
        tfHoras.setEnabled(false);
        dcFecha.setEnabled(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcular;
    private com.toedter.calendar.JDateChooser dcFecha;
    private javax.swing.JList<String> jListAsig;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JLabel labelHoras;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNota;
    private javax.swing.JPanel panelResumen;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfHoras;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNota;
    // End of variables declaration//GEN-END:variables
}
