/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.DetalleController;
import controlador.LoginController;
import java.text.SimpleDateFormat;
import java.util.Date;
import modelo.Asignatura;

/**
 *
 * @author alumno
 */
public class PanelDetalle extends javax.swing.JPanel {
    
    /**
     * Creates new form Visualiza1a1
     */
    public PanelDetalle() {
        
        initComponents();
        
        DetalleController.cargarDatos("SELECT * FROM ASIGNATURA WHERE CODPROFESOR = " 
                + LoginController.getProf().getCodProfesor());
        
        cargarDatos();
        updateBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDetalle = new javax.swing.JPanel();
        labelCodigo = new javax.swing.JLabel();
        labelProfesor = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        labelNota = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfProfesor = new javax.swing.JTextField();
        tfNota = new javax.swing.JTextField();
        botonAnterior = new javax.swing.JButton();
        botonSiguiente = new javax.swing.JButton();
        dcFecha = new com.toedter.calendar.JDateChooser();
        botonGuardar = new javax.swing.JButton();

        labelCodigo.setText("Código:");

        labelProfesor.setText("Profesor:");

        labelFecha.setText("Fecha:");

        labelNota.setText("Nota corte:");

        labelNombre.setText("Nombre:");

        botonAnterior.setText("Anterior");
        botonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnteriorActionPerformed(evt);
            }
        });

        botonSiguiente.setText("Siguiente");
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDetalleLayout = new javax.swing.GroupLayout(panelDetalle);
        panelDetalle.setLayout(panelDetalleLayout);
        panelDetalleLayout.setHorizontalGroup(
            panelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(panelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetalleLayout.createSequentialGroup()
                        .addGroup(panelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCodigo)
                            .addComponent(labelNombre)
                            .addComponent(labelProfesor)
                            .addComponent(labelFecha)
                            .addComponent(labelNota))
                        .addGap(37, 37, 37)
                        .addGroup(panelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(tfNombre)
                            .addComponent(tfProfesor)
                            .addComponent(tfNota)
                            .addComponent(dcFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetalleLayout.createSequentialGroup()
                        .addComponent(botonAnterior)
                        .addGap(29, 29, 29)
                        .addComponent(botonGuardar)
                        .addGap(26, 26, 26)
                        .addComponent(botonSiguiente)
                        .addGap(30, 30, 30))))
        );
        panelDetalleLayout.setVerticalGroup(
            panelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodigo)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProfesor)
                    .addComponent(tfProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelFecha)
                    .addComponent(dcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNota)
                    .addComponent(tfNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(panelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAnterior)
                    .addComponent(botonSiguiente)
                    .addComponent(botonGuardar))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnteriorActionPerformed
        DetalleController.prevAsig();
        mostrarAsig(DetalleController.getAsignatura());
        updateBotones();
    }//GEN-LAST:event_botonAnteriorActionPerformed

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        DetalleController.nextAsig();
        mostrarAsig(DetalleController.getAsignatura());
        updateBotones();
    }//GEN-LAST:event_botonSiguienteActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        Date nFecha = dcFecha.getDate();
        float nNota = Float.parseFloat(tfNota.getText());
        SimpleDateFormat sd = new SimpleDateFormat("MM/dd/yyyy");
        
        DetalleController.updateAsig("UPDATE ASIGNATURA SET FECHACORTE = '" + sd.format(nFecha)
                + "', NOTACORTE = " + nNota + " WHERE CODASIGNATURA = " 
                + DetalleController.getAsignatura().getCodAsignatura());
        
        DetalleController.cargarDatos("SELECT * FROM ASIGNATURA WHERE CODPROFESOR = " 
                + LoginController.getProf().getCodProfesor());
        
        cargarDatos();
        updateBotones();
    }//GEN-LAST:event_botonGuardarActionPerformed

    public void mostrarAsig(Asignatura a){
        tfCodigo.setText("" + a.getCodAsignatura());
        tfProfesor.setText("" + a.getCodProfesor());
        tfNombre.setText("" + a.getNombre());
        tfNota.setText("" + a.getNotaCorte());
        dcFecha.setCalendar(a.getFechaCorte());
    }
    
    public void updateBotones(){
        if(DetalleController.primero()){
            botonAnterior.setEnabled(false);
        }else{
            botonAnterior.setEnabled(true);
        }
        
        if(DetalleController.ultimo()){
            botonSiguiente.setEnabled(false);
        }else{
            botonSiguiente.setEnabled(true);
        }
    }
    
    public void cargarDatos(){
        mostrarAsig(DetalleController.getAsignatura());
        updateBotones();
        tfProfesor.setEnabled(false);
        tfCodigo.setEnabled(false);
        tfNombre.setEnabled(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAnterior;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonSiguiente;
    private com.toedter.calendar.JDateChooser dcFecha;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNota;
    private javax.swing.JLabel labelProfesor;
    private javax.swing.JPanel panelDetalle;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNota;
    private javax.swing.JTextField tfProfesor;
    // End of variables declaration//GEN-END:variables
}
