/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author alumno
 */
public class Gestor extends javax.swing.JFrame {

    private Panel1a1 pnl1a1;
    private PanelLogin pnlAcceder;
    private PanelTable pnlTable;
    
    /**
     * Creates new form Gestor
     */
    public Gestor() {
        pnl1a1 = null;
        pnlAcceder = null;
        pnlTable = null;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenu = new javax.swing.JMenuBar();
        menuLogin = new javax.swing.JMenu();
        itemCerrar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuVista = new javax.swing.JMenu();
        item1a1 = new javax.swing.JMenuItem();
        itemTable = new javax.swing.JMenuItem();
        itemUsuario = new javax.swing.JMenuItem();
        itemAltaLibro = new javax.swing.JMenuItem();
        itemBajaLibro = new javax.swing.JMenuItem();
        itemPresup = new javax.swing.JMenuItem();
        menuOtro = new javax.swing.JMenu();
        itemModPerfil = new javax.swing.JMenuItem();
        menuAcercaDe = new javax.swing.JMenu();
        itemInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Práctica 6");

        jLabel2.setText("Pedro Puertas Rodríguez");

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(96, 96, 96))))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addComponent(jLabel2)
                .addGap(53, 53, 53))
        );

        menuLogin.setText("Login");

        itemCerrar.setText("Abrir");
        itemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarActionPerformed(evt);
            }
        });
        menuLogin.add(itemCerrar);

        jMenuItem1.setText("Cerrar");
        menuLogin.add(jMenuItem1);

        jMenu.add(menuLogin);

        menuVista.setText("Vista");

        item1a1.setText("1 a 1");
        menuVista.add(item1a1);

        itemTable.setText("Table");
        menuVista.add(itemTable);

        itemUsuario.setText("Usuario");
        menuVista.add(itemUsuario);

        itemAltaLibro.setText("Alta libro");
        menuVista.add(itemAltaLibro);

        itemBajaLibro.setText("Baja libro");
        menuVista.add(itemBajaLibro);

        itemPresup.setText("Tienda");
        menuVista.add(itemPresup);

        jMenu.add(menuVista);

        menuOtro.setText("Otro");

        itemModPerfil.setText("Modificar perfil");
        menuOtro.add(itemModPerfil);

        jMenu.add(menuOtro);

        menuAcercaDe.setText("Acerca de");
        menuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcercaDeActionPerformed(evt);
            }
        });

        itemInfo.setText("Info");
        itemInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInfoActionPerformed(evt);
            }
        });
        menuAcercaDe.add(itemInfo);

        jMenu.add(menuAcercaDe);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcercaDeActionPerformed
        
        
        
    }//GEN-LAST:event_menuAcercaDeActionPerformed

    private void itemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarActionPerformed
        
        
        
    }//GEN-LAST:event_itemCerrarActionPerformed

    private void itemInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem item1a1;
    private javax.swing.JMenuItem itemAltaLibro;
    private javax.swing.JMenuItem itemBajaLibro;
    private javax.swing.JMenuItem itemCerrar;
    private javax.swing.JMenuItem itemInfo;
    private javax.swing.JMenuItem itemModPerfil;
    private javax.swing.JMenuItem itemPresup;
    private javax.swing.JMenuItem itemTable;
    private javax.swing.JMenuItem itemUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JMenu menuAcercaDe;
    private javax.swing.JMenu menuLogin;
    private javax.swing.JMenu menuOtro;
    private javax.swing.JMenu menuVista;
    // End of variables declaration//GEN-END:variables
}
