/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.LoginController;
import javax.swing.ImageIcon;
import modelo.Tienda;
import modelo.Trabajador;

/**
 *
 * @author alumno
 */
public class PanelTrabajador extends javax.swing.JPanel {

    private boolean modificar;
    
    /**
     * Creates new form PanelTrabajador
     */
    public PanelTrabajador(boolean modificar) {
        
        this.modificar = modificar;
        
        initComponents();

        comprobarBotones();
        cargarDatos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTrabajador = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblSalario = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        lblApe = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dcFecha = new com.toedter.calendar.JDateChooser();
        btnFoto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfApe = new javax.swing.JTextField();
        tfSalario = new javax.swing.JTextField();
        tfDni = new javax.swing.JTextField();
        tfTienda = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        fcFoto = new javax.swing.JFileChooser();

        lblNombre.setText("Nombre:");

        lblSalario.setText("Salario:");

        lblFoto.setText("FOTO");

        lblApe.setText("Apellidos:");

        lblDni.setText("DNI:");

        jLabel1.setText("Contratación:");

        btnFoto.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnFoto.setText("Cambiar foto");
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Tienda:");

        btnGuardar.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnGuardar.setText("Guardar cambios");

        fcFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTrabajadorLayout = new javax.swing.GroupLayout(pnlTrabajador);
        pnlTrabajador.setLayout(pnlTrabajadorLayout);
        pnlTrabajadorLayout.setHorizontalGroup(
            pnlTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrabajadorLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(lblDni)
                    .addComponent(jLabel1)
                    .addComponent(lblSalario)
                    .addComponent(lblApe)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNombre)
                    .addComponent(tfApe)
                    .addComponent(tfSalario)
                    .addComponent(tfDni)
                    .addComponent(dcFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(tfTienda))
                .addGap(52, 52, 52)
                .addGroup(pnlTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFoto)
                    .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTrabajadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(141, 141, 141))
            .addGroup(pnlTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTrabajadorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fcFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlTrabajadorLayout.setVerticalGroup(
            pnlTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrabajadorLayout.createSequentialGroup()
                .addGroup(pnlTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTrabajadorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(141, 141, 141))
                    .addGroup(pnlTrabajadorLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(pnlTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApe)
                            .addComponent(tfApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSalario)
                            .addComponent(tfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDni)
                            .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(dcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFoto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)))
                .addComponent(btnGuardar)
                .addGap(28, 28, 28))
            .addGroup(pnlTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTrabajadorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fcFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        fcFoto.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        
        fcFoto.setVisible(true);
        
    }//GEN-LAST:event_btnFotoActionPerformed

    private void fcFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcFotoActionPerformed
       
        fcFoto.setVisible(false);
        
    }//GEN-LAST:event_fcFotoActionPerformed

    public void comprobarBotones(){
        
        if(modificar){
            fcFoto.setVisible(true);
            btnFoto.setVisible(true);
            btnGuardar.setVisible(true);
            tfDni.setEnabled(true);
            tfNombre.setEnabled(false);
            tfApe.setEnabled(false);
            tfSalario.setEnabled(false);
            tfTienda.setEnabled(false);
        }else{
            btnFoto.setVisible(false);
            btnGuardar.setVisible(false);
            tfDni.setEnabled(false);
            tfNombre.setEnabled(false);
            tfApe.setEnabled(false);
            tfSalario.setEnabled(false);
            tfTienda.setEnabled(false);
        }
        
    }
    
    private void cargarDatos() {
        Trabajador t = LoginController.getTrabajador();
        
        tfDni.setText(t.getDni());
        tfNombre.setText(t.getNombre());
        tfApe.setText(t.getApellidos());
        tfSalario.setText("" + t.getSalario());
        tfTienda.setText("" + t.getTienda());
        lblFoto.setIcon(new ImageIcon(System.getProperty("user.dir") 
                + "/src/fotos/" + t.getFoto()));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnGuardar;
    private com.toedter.calendar.JDateChooser dcFecha;
    private javax.swing.JFileChooser fcFoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblApe;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JPanel pnlTrabajador;
    private javax.swing.JTextField tfApe;
    private javax.swing.JTextField tfDni;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfSalario;
    private javax.swing.JTextField tfTienda;
    // End of variables declaration//GEN-END:variables
}